### PR TITLE
Disable multi thread git deps synchronization

### PR DESCRIPTION
**Pull request by amiralies**

### CODE REVIEW

**Comment by amiralies** [comment]
multi threaded git fetches cause problems on lower bandwidth networks, I faced this issue when building onivim.
I think this doesn't have huge impact on higher bandwidth networks but makes the dep sync step very slow (or in my case always timeout) on lower bandwidths

**Comment by glennsl** [comment]
Trying CI again after unbreaking the macOS VM in #17

**Comment by bryphe** [comment]
Thanks @amiralies for investigating this! Much appreciated.

**Pull request merged**
